# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: Build
    displayName: 'LTIWEBAPPREPO-CALLING'
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: LTIWEBAPPDEMO
      clean: true
    - task: CopyFiles@2
      displayName: 'copy file'
      inputs:
          SourceFolder: $(Build.SourcesDirectory)
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          Content: '**'
